name: gov_connect
description: "Citizen-focused mobile application that enables access to any government service through a unified platform."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and icons
  cupertino_icons: ^1.0.8
  flutter_remix: ^0.0.3
  remixicon: ^1.0.0

  # Media and scanning
  video_player: ^2.8.2
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  # HTTP and API
  dio: ^5.7.0

  # Local storage and state management
  shared_preferences: ^2.3.2

  # State management
  provider: ^6.1.2

  # JWT token utilities
  jwt_decoder: ^2.0.1

  # Secure storage for sensitive data
  flutter_secure_storage: ^9.2.2

  # Passkey authentication
  passkeys: ^2.12.0
  http: ^1.2.1
  # OpenStreetMap for location display (Free alternative to Google Maps)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # URL launcher for external links
  url_launcher: ^6.3.1
  go_router: ^16.1.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  # Local notifications
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#1565c0"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons_imported/
    - assets/qrflow_images/
