name: gov_connect
description: "Citizen-focused mobile application that enables access to any government service through a unified platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and icons
  cupertino_icons: ^1.0.8
  flutter_remix: ^0.0.3
  remixicon: ^1.0.0

  # Media and scanning
  video_player: ^2.8.2
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  # HTTP and API
  dio: ^5.7.0

  # Local storage and state management
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2

  # JWT utilities
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#1565c0"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons_imported/
    - assets/qrflow_images/
