services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: govconnect-database-dev
    environment:
      POSTGRES_DB: govconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - govconnect-network-dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: govconnect-backend-dev
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        while ! nc -z database 5432; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        npm run start:dev
      "
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: govconnect
      JWT_SECRET: development-secret-key
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      MAIL_HOST: mail-dev
      MAIL_PORT: 1025
      MAIL_FROM: noreply@govconnect.com
      DB_SYNCHRONIZE: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - database
    networks:
      - govconnect-network-dev
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # File Storage Service (MinIO S3-compatible)
  file-storage:
    image: minio/minio:latest
    container_name: govconnect-file-storage-dev
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data_dev:/data
    command: server /data --console-address ":9001"
    networks:
      - govconnect-network-dev
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Mail Development Server (MailHog)
  mail-dev:
    image: mailhog/mailhog:latest
    container_name: govconnect-mail-dev-server
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # Web UI port
    networks:
      - govconnect-network-dev
    restart: unless-stopped

networks:
  govconnect-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  node_modules:
  minio_data_dev:
