import { MigrationInterface, QueryRunner } from "typeorm";

export class AddFcmTokenToUsers1755335459466 implements MigrationInterface {
    name = 'AddFcmTokenToUsers1755335459466'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" DROP CONSTRAINT "FK_dynamic_form_fields_sectionId"`);
        await queryRunner.query(`ALTER TABLE "form_sections" DROP CONSTRAINT "FK_form_sections_formId"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_form_submissions_formId"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_form_submissions_userId"`);
        await queryRunner.query(`ALTER TABLE "field_attributes" DROP CONSTRAINT "FK_field_attributes_field"`);
        await queryRunner.query(`ALTER TABLE "form_responses" DROP CONSTRAINT "FK_form_responses_service"`);
        await queryRunner.query(`ALTER TABLE "form_responses" DROP CONSTRAINT "FK_form_responses_user"`);
        await queryRunner.query(`ALTER TABLE "form_response_values" DROP CONSTRAINT "FK_form_response_values_response"`);
        await queryRunner.query(`ALTER TABLE "form_response_values" DROP CONSTRAINT "FK_form_response_values_field"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_fields_field_type"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_form_fields_service"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_form_fields_field"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_services_department"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_chat_sessions_userId"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_userId"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP CONSTRAINT "FK_02227b9a8a34a808e3e23800b00"`);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" DROP CONSTRAINT "FK_faq_question_tags_faqQuestionId"`);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" DROP CONSTRAINT "FK_faq_question_tags_tagId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dynamic_form_fields_sectionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_sections_formId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submissions_formId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submissions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submissions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_field_attributes_field_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_responses_service_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_responses_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_responses_submitted_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_response_values_response_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_response_values_field_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fields_ftype_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_service_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_field_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_services_department_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faq_questions_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tags_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_messages_sessionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faq_question_tags_faqQuestionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faq_question_tags_tagId"`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" DROP CONSTRAINT "CHK_dynamic_form_fields_fieldType"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "CHK_form_submissions_status"`);
        // Skip renaming passkey_challenge to fcm_token as fcm_token already exists
        // Skip creating notifications table as it already exists
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "fieldValues"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP CONSTRAINT "UQ_81b80835fab9dcadaebc6d168ab"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "credential_id"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "public_key"`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "credential_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD CONSTRAINT "UQ_81b80835fab9dcadaebc6d168ab" UNIQUE ("credential_id")`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "public_key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "display_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "submissionData" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "reviewNotes" text`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "reviewedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "reviewedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "credentialId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD CONSTRAINT "UQ_fca092c48965a076c32c58f3b0c" UNIQUE ("credentialId")`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "publicKey" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "transports" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fcm_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fcm_token" character varying`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" DROP COLUMN "fieldType"`);
        await queryRunner.query(`CREATE TYPE "public"."dynamic_form_fields_fieldtype_enum" AS ENUM('text', 'phone_number', 'email', 'document_upload', 'date', 'dropdown', 'radio_button', 'checkbox', 'textarea', 'number', 'dependency_form')`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" ADD "fieldType" "public"."dynamic_form_fields_fieldtype_enum" NOT NULL DEFAULT 'text'`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."form_submissions_status_enum" AS ENUM('draft', 'submitted', 'under_review', 'approved', 'rejected', 'completed')`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "status" "public"."form_submissions_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "counter"`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "counter" bigint NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_cc43f819988ed1138cc9b0f7c5" ON "faq_question_tags" ("faqQuestionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_28f6a249c186cda73a379e2b8f" ON "faq_question_tags" ("tagId") `);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD CONSTRAINT "FK_02227b9a8a34a808e3e23800b00" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        // Skip adding notifications foreign key as it's managed by a separate migration
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" ADD CONSTRAINT "FK_ef99f0401381b690eea3253230d" FOREIGN KEY ("sectionId") REFERENCES "form_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_sections" ADD CONSTRAINT "FK_562e6c04ee8ba0f4136540074b8" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_04697a76570644ee4b624575bdb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_6bb44ead8acd515f1333e5309bf" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_120933f2fe841a3a6cee150d387" FOREIGN KEY ("reviewedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "field_attributes" ADD CONSTRAINT "FK_e1cef48c295ff4d6a15ad63a15d" FOREIGN KEY ("field_id") REFERENCES "fields"("field_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_responses" ADD CONSTRAINT "FK_2bf2b75692f3d4798e6f36b551e" FOREIGN KEY ("service_id") REFERENCES "services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_responses" ADD CONSTRAINT "FK_9b3073ddffd62f8196971a0022e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_response_values" ADD CONSTRAINT "FK_0643ac82da60afc2a515f62a5bc" FOREIGN KEY ("response_id") REFERENCES "form_responses"("response_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_response_values" ADD CONSTRAINT "FK_7eabdae38f34edc992abc460a58" FOREIGN KEY ("field_id") REFERENCES "fields"("field_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_a8a48fb309772b474e97a4f0ee0" FOREIGN KEY ("ftype_id") REFERENCES "field_types"("ftype_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_0f8f68181ca33ad636625359859" FOREIGN KEY ("service_id") REFERENCES "services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_791e05417236f98237ca86b5a1a" FOREIGN KEY ("field_id") REFERENCES "fields"("field_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_fe8dcab94e4095af071399c6523" FOREIGN KEY ("department_id") REFERENCES "departments"("department_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_d0320df1059d8a029a460f4161d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_43d968962b9e24e1e3517c0fbff" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" ADD CONSTRAINT "FK_cc43f819988ed1138cc9b0f7c59" FOREIGN KEY ("faqQuestionId") REFERENCES "faq_questions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" ADD CONSTRAINT "FK_28f6a249c186cda73a379e2b8f6" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "faq_question_tags" DROP CONSTRAINT "FK_28f6a249c186cda73a379e2b8f6"`);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" DROP CONSTRAINT "FK_cc43f819988ed1138cc9b0f7c59"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_43d968962b9e24e1e3517c0fbff"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_d0320df1059d8a029a460f4161d"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_fe8dcab94e4095af071399c6523"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_791e05417236f98237ca86b5a1a"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_0f8f68181ca33ad636625359859"`);
        await queryRunner.query(`ALTER TABLE "fields" DROP CONSTRAINT "FK_a8a48fb309772b474e97a4f0ee0"`);
        await queryRunner.query(`ALTER TABLE "form_response_values" DROP CONSTRAINT "FK_7eabdae38f34edc992abc460a58"`);
        await queryRunner.query(`ALTER TABLE "form_response_values" DROP CONSTRAINT "FK_0643ac82da60afc2a515f62a5bc"`);
        await queryRunner.query(`ALTER TABLE "form_responses" DROP CONSTRAINT "FK_9b3073ddffd62f8196971a0022e"`);
        await queryRunner.query(`ALTER TABLE "form_responses" DROP CONSTRAINT "FK_2bf2b75692f3d4798e6f36b551e"`);
        await queryRunner.query(`ALTER TABLE "field_attributes" DROP CONSTRAINT "FK_e1cef48c295ff4d6a15ad63a15d"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_120933f2fe841a3a6cee150d387"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_6bb44ead8acd515f1333e5309bf"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_04697a76570644ee4b624575bdb"`);
        await queryRunner.query(`ALTER TABLE "form_sections" DROP CONSTRAINT "FK_562e6c04ee8ba0f4136540074b8"`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" DROP CONSTRAINT "FK_ef99f0401381b690eea3253230d"`);
        // Skip dropping notifications constraint as it's managed by a separate migration
        await queryRunner.query(`ALTER TABLE "passkeys" DROP CONSTRAINT "FK_02227b9a8a34a808e3e23800b00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28f6a249c186cda73a379e2b8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc43f819988ed1138cc9b0f7c5"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "counter"`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "counter" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."form_submissions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" DROP COLUMN "fieldType"`);
        await queryRunner.query(`DROP TYPE "public"."dynamic_form_fields_fieldtype_enum"`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" ADD "fieldType" character varying NOT NULL DEFAULT 'text'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fcm_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fcm_token" text`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "transports"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "publicKey"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP CONSTRAINT "UQ_fca092c48965a076c32c58f3b0c"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "credentialId"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "reviewedAt"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "reviewedBy"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "reviewNotes"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP COLUMN "submissionData"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "public_key"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP CONSTRAINT "UQ_81b80835fab9dcadaebc6d168ab"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP COLUMN "credential_id"`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "public_key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "display_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD "credential_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD CONSTRAINT "UQ_81b80835fab9dcadaebc6d168ab" UNIQUE ("credential_id")`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "submittedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD "fieldValues" json NOT NULL DEFAULT '[]'`);
        // Skip dropping notifications table as it's managed by a separate migration
        // Skip renaming fcm_token back to passkey_challenge as fcm_token was not renamed from it
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "CHK_form_submissions_status" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'submitted'::character varying, 'under_review'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" ADD CONSTRAINT "CHK_dynamic_form_fields_fieldType" CHECK ((("fieldType")::text = ANY ((ARRAY['text'::character varying, 'phone_number'::character varying, 'email'::character varying, 'document_upload'::character varying, 'date'::character varying, 'dropdown'::character varying, 'radio_button'::character varying, 'checkbox'::character varying, 'textarea'::character varying, 'number'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "IDX_faq_question_tags_tagId" ON "faq_question_tags" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_faq_question_tags_faqQuestionId" ON "faq_question_tags" ("faqQuestionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_messages_sessionId" ON "chat_messages" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_userId" ON "chat_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_tags_category" ON "tags" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_faq_questions_category" ON "faq_questions" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_services_department_id" ON "services" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_field_id" ON "form_fields" ("field_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_service_id" ON "form_fields" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fields_ftype_id" ON "fields" ("ftype_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_response_values_field_id" ON "form_response_values" ("field_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_response_values_response_id" ON "form_response_values" ("response_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_responses_submitted_at" ON "form_responses" ("submitted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_responses_user_id" ON "form_responses" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_responses_service_id" ON "form_responses" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_field_attributes_field_id" ON "field_attributes" ("field_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submissions_status" ON "form_submissions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submissions_userId" ON "form_submissions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submissions_formId" ON "form_submissions" ("formId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_sections_formId" ON "form_sections" ("formId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dynamic_form_fields_sectionId" ON "dynamic_form_fields" ("sectionId") `);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" ADD CONSTRAINT "FK_faq_question_tags_tagId" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faq_question_tags" ADD CONSTRAINT "FK_faq_question_tags_faqQuestionId" FOREIGN KEY ("faqQuestionId") REFERENCES "faq_questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD CONSTRAINT "FK_02227b9a8a34a808e3e23800b00" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_chat_sessions_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_services_department" FOREIGN KEY ("department_id") REFERENCES "departments"("department_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_form_fields_field" FOREIGN KEY ("field_id") REFERENCES "fields"("field_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_form_fields_service" FOREIGN KEY ("service_id") REFERENCES "services"("service_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fields" ADD CONSTRAINT "FK_fields_field_type" FOREIGN KEY ("ftype_id") REFERENCES "field_types"("ftype_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_response_values" ADD CONSTRAINT "FK_form_response_values_field" FOREIGN KEY ("field_id") REFERENCES "fields"("field_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_response_values" ADD CONSTRAINT "FK_form_response_values_response" FOREIGN KEY ("response_id") REFERENCES "form_responses"("response_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_responses" ADD CONSTRAINT "FK_form_responses_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_responses" ADD CONSTRAINT "FK_form_responses_service" FOREIGN KEY ("service_id") REFERENCES "services"("service_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "field_attributes" ADD CONSTRAINT "FK_field_attributes_field" FOREIGN KEY ("field_id") REFERENCES "fields"("field_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_form_submissions_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_form_submissions_formId" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_sections" ADD CONSTRAINT "FK_form_sections_formId" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dynamic_form_fields" ADD CONSTRAINT "FK_dynamic_form_fields_sectionId" FOREIGN KEY ("sectionId") REFERENCES "form_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
